# Form implementation generated from reading ui file '.\ui\dev\prova.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(260, 80, 75, 24))
        self.pushButton.setObjectName("pushButton")
        self.connectionLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.connectionLabel.setGeometry(QtCore.QRect(380, 80, 91, 21))
        self.connectionLabel.setObjectName("connectionLabel")
        self.ip = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ip.setGeometry(QtCore.QRect(100, 80, 113, 22))
        self.ip.setObjectName("ip")
        self.name = QtWidgets.QLabel(parent=self.centralwidget)
        self.name.setGeometry(QtCore.QRect(390, 140, 49, 16))
        self.name.setObjectName("name")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionConnection = QtGui.QAction(parent=MainWindow)
        self.actionConnection.setObjectName("actionConnection")
        self.actionAbout = QtGui.QAction(parent=MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionconnecting = QtGui.QAction(parent=MainWindow)
        self.actionconnecting.setObjectName("actionconnecting")

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(self.actionconnecting.trigger) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Connect"))
        self.connectionLabel.setText(_translate("MainWindow", "disconected"))
        self.name.setText(_translate("MainWindow", "Unk"))
        self.actionConnection.setText(_translate("MainWindow", "Connection"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionconnecting.setText(_translate("MainWindow", "connecting"))
