# Form implementation generated from reading ui file '.\ui\dev\prova.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(873, 760)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.CameraConect = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.CameraConect.setObjectName("CameraConect")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.CameraConect)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ConnectButton = QtWidgets.QPushButton(parent=self.CameraConect)
        self.ConnectButton.setObjectName("ConnectButton")
        self.verticalLayout.addWidget(self.ConnectButton)
        self.statusLabel = QtWidgets.QLabel(parent=self.CameraConect)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout.addWidget(self.statusLabel)
        self.name = QtWidgets.QLabel(parent=self.CameraConect)
        self.name.setObjectName("name")
        self.verticalLayout.addWidget(self.name)
        self.verticalLayout_2.addWidget(self.CameraConect)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.discoverButton = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.discoverButton.setGeometry(QtCore.QRect(120, 40, 75, 24))
        self.discoverButton.setObjectName("discoverButton")
        self.ipedit = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.ipedit.setGeometry(QtCore.QRect(70, 110, 113, 22))
        self.ipedit.setInputMask("")
        self.ipedit.setObjectName("ipedit")
        self.verticalLayout_2.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 873, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionConnection = QtGui.QAction(parent=MainWindow)
        self.actionConnection.setObjectName("actionConnection")
        self.actionDiscover = QtGui.QAction(parent=MainWindow)
        self.actionDiscover.setObjectName("actionDiscover")

        self.retranslateUi(MainWindow)
        self.discoverButton.clicked.connect(self.actionDiscover.trigger) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CameraConect.setTitle(_translate("MainWindow", "Connect to Camera"))
        self.ConnectButton.setText(_translate("MainWindow", "Connect"))
        self.statusLabel.setText(_translate("MainWindow", "disconected"))
        self.name.setText(_translate("MainWindow", "Unk"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Discover"))
        self.discoverButton.setText(_translate("MainWindow", "Discover"))
        self.ipedit.setText(_translate("MainWindow", "ip"))
        self.actionConnection.setText(_translate("MainWindow", "Connect"))
        self.actionDiscover.setText(_translate("MainWindow", "Discover"))
