# Form implementation generated from reading ui file '.\ui\dev\prova.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(464, 289)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.groupBox)
        self.textBrowser.setGeometry(QtCore.QRect(180, 30, 256, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 158, 71))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.ipLineEdit = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        self.ipLineEdit.setMaximumSize(QtCore.QSize(120, 21))
        self.ipLineEdit.setObjectName("ipLineEdit")
        self.gridLayout.addWidget(self.ipLineEdit, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.statusLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.statusLabel.setObjectName("statusLabel")
        self.gridLayout.addWidget(self.statusLabel, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.connectButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.connectButton.setObjectName("connectButton")
        self.verticalLayout_3.addWidget(self.connectButton)
        self.verticalLayout_2.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 464, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.actionConnection = QtGui.QAction(parent=MainWindow)
        self.actionConnection.setObjectName("actionConnection")
        self.actionDiscover = QtGui.QAction(parent=MainWindow)
        self.actionDiscover.setObjectName("actionDiscover")

        self.retranslateUi(MainWindow)
        self.connectButton.clicked.connect(self.actionConnection.trigger) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Camera"))
        self.label.setText(_translate("MainWindow", "status: "))
        self.ipLineEdit.setText(_translate("MainWindow", "192.168.1.88"))
        self.label_3.setText(_translate("MainWindow", "ip: "))
        self.statusLabel.setText(_translate("MainWindow", "disconnected"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.actionConnection.setText(_translate("MainWindow", "Connect"))
        self.actionDiscover.setText(_translate("MainWindow", "Discover"))
